language: java
jdk: oraclejdk8
sudo: false

before_install: chmod +x gradlew
script:
  - ./gradlew check

cache:
  directories:
  - ~/.gradle

notifications:
  irc:
    channels:
      - "irc.esper.net#shadowfacts"
    on_success: always
    on_failure: always
    skip_join: true
  email: false